# Generated by Django 5.1.7 on 2025-08-01 12:18

import json

from django.db import migrations


def create_hourly_sync_task(apps, schema_editor):
    """
    Create a periodic task to sync external prices hourly.
    This task will update the external_price field of all Item instances.
    """
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = IntervalSchedule.objects.get_or_create(every=1, period="hours")

    PeriodicTask.objects.get_or_create(
        name="Hourly external price sync",
        defaults={
            "interval": schedule,
            "task": "items.tasks.hourly_external_price_sync",
            "kwargs": json.dumps({}),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_external_price"),
        ("django_celery_beat", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_hourly_sync_task),
    ]
